cache: bundler
sudo: false

before_install:
  - gem install bundler

rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-9000
  - rbx-3

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9000
    - rvm: rbx-3

script:
  - bundle exec bin/test_runner
  - CODECLIMATE_REPO_TOKEN=35f688ab9034adbb1f1f705880cae769409ac19dff515205e69765714697fa7f bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: 35f688ab9034adbb1f1f705880cae769409ac19dff515205e69765714697fa7f

notifications:
  email:
    recipients:
      - benny.klotz92@gmail.com
    email:
      on_failure: change
      on_success: change
